# Reference files
reference: "reference/chr1.fa"
bedfile: "chr17plus.interval_list"

# Sample Configuration
sample_sheet: "config/samples.tsv"  # Path to TSV file


#NormalName: -normal HCC1143_BL -normal  ATOMGD19_replacement

#resources for specific tool here 130000=130gb and 100000=100gb
statThreads: 4
statRam: 30000
statDisk: 30000

bwathreads: 15
bwaRam: 130000
bwaDisk: 100000

annotationThreads: 8
annotationRam: 64000
annotationDisk: 50000

gatkThreads: 15
gatkRam: 130000
gatkDisk: 100000

samtoolsThreads: 8
samtoolsRam: 50000
samtoolsDisk: 80000

filterToolsThreads: 4
filterToolsRam: 30000
filterToolsDisk: 30000


#database
dbSNP: database/00-common_all.vcf.gz
dbSNP_index: database/00-common_all.vcf.gz.tbi

clinVar: database/clinvar_20250421.vcf.gz
clinVar_index: database/clinvar_20250421.vcf.gz.tbi

#known sites, used in base recalibration
known_Sites: database/00-common_all.vcf.gz
known_Sites_index: database/00-common_all.vcf.gz.tbi

#resources & pon
af: resources/af-only-gnomad.hg38.vcf.gz
af_index: resources/af-only-gnomad.hg38.vcf.gz.tbi

crsp: resources/1000g_pon.hg38.vcf.gz
crsp_index: resources/1000g_pon.hg38.vcf.gz.tbi

exac: resources/small_exac_common_3.hg38.vcf.gz
exac_index: resources/small_exac_common_3.hg38.vcf.gz

#Funcotator data resources
data_sources: resources/funcotator_dataSources.v1.8.hg38.20230908s.tar.gz
folder: funcotator_dataSources.v1.8.hg38.20230908s
